const ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    CART_ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
    OUT_OF_STOCK: "OUT_OF_STOCK",
    PROMO_INVALID: "PROMO_INVALID",
    PROMO_EXPIRED: "PROMO_EXPIRED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
  };

const DEFAULT_MESSAGES = {
    [ERROR_CODES.BAD_REQUEST]: "Bad request parameters",
    [ERROR_CODES.VALIDATION_ERROR]: "Please check your input",
    [ERROR_CODES.AUTH_UNAUTHORIZED]: "Please login first",
    [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: "Incorrect username or password",
    [ERROR_CODES.PERMISSION_DENIED]: "Permission denied",
    [ERROR_CODES.RESOURCE_NOT_FOUND]: "Resource not found",
    [ERROR_CODES.PRODUCT_NOT_FOUND]: "Product not found",
    [ERROR_CODES.CART_ITEM_NOT_FOUND]: "Item not found in cart",
    [ERROR_CODES.OUT_OF_STOCK]: "Out of stock",
    [ERROR_CODES.PROMO_INVALID]: "Invalid promo code",
    [ERROR_CODES.PROMO_EXPIRED]: "Promo code expired",
    [ERROR_CODES.INTERNAL_ERROR]: "System busy, please try again later",
    [ERROR_CODES.SERVICE_UNAVAILABLE]: "Service unavailable"
  };

  export { ERROR_CODES, DEFAULT_MESSAGES };

