const ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    CART_ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
    OUT_OF_STOCK: "OUT_OF_STOCK",
    PROMO_INVALID: "PROMO_INVALID",
    PROMO_EXPIRED: "PROMO_EXPIRED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
  };

const DEFAULT_MESSAGES = {
    [ERROR_CODES.BAD_REQUEST]: "请求参数有误",
    [ERROR_CODES.VALIDATION_ERROR]: "请检查输入内容",
    [ERROR_CODES.AUTH_UNAUTHORIZED]: "请先登录",
    [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: "账号或密码错误",
    [ERROR_CODES.PERMISSION_DENIED]: "权限不足",
    [ERROR_CODES.RESOURCE_NOT_FOUND]: "资源不存在",
    [ERROR_CODES.PRODUCT_NOT_FOUND]: "未找到该商品",
    [ERROR_CODES.CART_ITEM_NOT_FOUND]: "购物车中未找到该商品",
    [ERROR_CODES.OUT_OF_STOCK]: "库存不足",
    [ERROR_CODES.PROMO_INVALID]: "优惠码无效",
    [ERROR_CODES.PROMO_EXPIRED]: "优惠码已过期",
    [ERROR_CODES.INTERNAL_ERROR]: "系统繁忙，请稍后再试",
    [ERROR_CODES.SERVICE_UNAVAILABLE]: "服务暂不可用"
  };

  export default { ERROR_CODES, DEFAULT_MESSAGES };

